<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>at365.WallpaperSlideshow</RootNamespace>
    <ApplicationIcon>resources\icon.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
    <PublishDir>$(MSBuildProjectDirectory)\publish\</PublishDir>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tests\**\*.cs" />
    <InternalsVisibleTo Include="WallpaperSlideshow.RegressionTests" />
    <Content Include="resources\icon.ico" />
    <EmbeddedResource Include="config.json" />
    <EmbeddedResource Include="resources\paused.ico" LogicalName="at365.WallpaperSlideshow.paused.ico" />
    <EmbeddedResource Include="resources\running.ico" LogicalName="at365.WallpaperSlideshow.running.ico" />
  </ItemGroup>

</Project>
